CREATE TABLE IF NOT EXISTS vehicles (
  id VARCHAR(50) PRIMARY KEY,
  driver_name VARCHAR(255) NOT NULL,
  corridor VARCHAR(50) NOT NULL,
  speed DOUBLE NOT NULL DEFAULT 0,
  fuel INT NOT NULL DEFAULT 100,
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  vehicle_type VARCHAR(50) NOT NULL,
  latitude DOUBLE NOT NULL,
  longitude DOUBLE NOT NULL,
  last_update TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS routes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vehicle_id VARCHAR(50) NOT NULL,
  start_location VARCHAR(255) NOT NULL,
  end_location VARCHAR(255) NOT NULL,
  distance DOUBLE NOT NULL,
  duration INT NOT NULL,
  avg_speed DOUBLE NOT NULL,
  stops INT NOT NULL DEFAULT 0,
  date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_routes_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);

CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vehicle_id VARCHAR(50) NOT NULL,
  type VARCHAR(50) NOT NULL,
  message VARCHAR(255) NOT NULL,
  severity VARCHAR(50) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_alerts_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);

CREATE TABLE IF NOT EXISTS daily_metrics (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vehicle_id VARCHAR(50) NOT NULL,
  date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  total_distance DOUBLE NOT NULL DEFAULT 0,
  fuel_efficiency DOUBLE NOT NULL DEFAULT 0,
  avg_speed DOUBLE NOT NULL DEFAULT 0,
  CONSTRAINT fk_metrics_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);

